apiVersion: ENC[AES256_GCM,data:0sA=,iv:IkGUHWQ6aYHN9swzyZ56OutwxMFc8Eff8ZSSa5vO7TE=,tag:OYyYjLTRxVaUC3qtvYR/7A==,type:str]
kind: ENC[AES256_GCM,data:kcvs4dnqB+Us,iv:10OwwKDvqCYI7B0iKYGPZ2CWwjOB4Vl5oLG5dsJYFr0=,tag:xcJn1rVReSisJGygsnaCMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mTN1bu4hCw==,iv:gqnwIxxOKZ9/gOobd/mTQ0zl5n+TiFGLHWzTPOPgsLA=,tag:asXY0vRCLnKW4hem51ODew==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bWt0UHF4Tzg2OE5rb0Nu
            MEF2WGRWSWdoZUVqcE5lME9BcllpMlN1OW4wCmtjUUZWN1pIRVAyMEFTRnVIQ0Yw
            Q0FsbGJoenhXU29OWVN0ekoyZVc3WWMKLS0tIHpjVHdKTTFlS0ozanlBc0Rvazdu
            YVV4azA4SWRKa09FaUVQS1NUYk5EZTgKa3fW9HGTSOz/bHh1G1zxHza157NlAfli
            7jPHxlHHI1c8UZdfOF1CNyb79cdwjVJF1eqcm/pAX6PT/P/BCNwJiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:49:11Z"
    mac: ENC[AES256_GCM,data:AutMfvrFI6v2b3r4CtrYSB8iuOY5dUuXV5DTF7DNVlRrdjXQpwduSJH++CFB8kbqakPYJ2PZeXCEfFrkgVEcVocKbOXcuItK4/yhJXT0NPJWdLyXsT9TQzrEmeycrKCxyi1HyT0AkQBZVj323l/J1o6/ZDBl77WvcVMN3VvMLvc=,iv:r/QI5jNkvVnG1uC0JiazQFF3ag2o1ANicI2zGYUD4rk=,tag:JhCOFoMnlkrIaFhufx1LNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:0sA=,iv:IkGUHWQ6aYHN9swzyZ56OutwxMFc8Eff8ZSSa5vO7TE=,tag:OYyYjLTRxVaUC3qtvYR/7A==,type:str]
kind: ENC[AES256_GCM,data:nSDX3FK/,iv:0ceG+qS3rkwClLXU1WXcOJ1eMm3aHbj2G1LzT1qoOwA=,tag:KAJD2NTvoMNfgDELgum+qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:weROJ0GW8JhSztlfxLBI,iv:gdzPY/Dj3mGmu6T/OP7K+aTd22i0LhdnMse1t0OJDrQ=,tag:/KQbLMeVBo5AlyiQGUuBFg==,type:str]
    namespace: ENC[AES256_GCM,data:cvHLFzs58g==,iv:4ATjHD1VLOR3CxcthLyV0Y3cwSOczc5j3L4A/nUczO4=,tag:DEEXqMcmtr9x2HpMQ/Qd0A==,type:str]
type: ENC[AES256_GCM,data:QT0wkqxd,iv:Q42arTxTbPGGCOBHpyX6URLb3Ea9Bh0Va7fWk0abrUM=,tag:h4z5fZR2sBmjSq6blz3wPA==,type:str]
stringData:
    adminUsername: ENC[AES256_GCM,data:1Na6WcA=,iv:oUdxF9T2my5ppgFF9r6930xHdn6zCdzVSrr3o7GEKqk=,tag:CDVN18a5pVAuxjR1w4VXPg==,type:str]
    adminPassword: ENC[AES256_GCM,data:ab1VYHclq5Yr+CdjliHXEQ==,iv:QaDWCvMRlkHCftdR3ExJeqhj7x3W5h5oAwUhPojD81Y=,tag:UZNRInPWRr0sFa68xqgtTg==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:v5Fbga+LXn45Vgqc2/3H0+plOKwNlwNW/nNuJeXi1D1EBTblB+3I+iHg2uHItT1fX4vrqtTCaHQ9YYEtRqs7ng==,iv:HM1zg/aofBGL6yyvmuY6rUldKCsKFHXOSS8YFRY/oOU=,tag:gRAsn4w0VRoDm283I8g5DA==,type:str]
    erlangCookie: ENC[AES256_GCM,data:yiBvWiJt364VL6mt4tezzlnbFOBSvBZnn1HKG/yGABxNSNa086RZYfbQlbRn764y/fuP/0FtFTHUCn5jk4m8jg==,iv:CH+4sKI2VlMevFyqh85xJDbWHdNDwTi1LGbGSflBCRU=,tag:5GqJ25dH5xDDV0gINyUjUA==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bWt0UHF4Tzg2OE5rb0Nu
            MEF2WGRWSWdoZUVqcE5lME9BcllpMlN1OW4wCmtjUUZWN1pIRVAyMEFTRnVIQ0Yw
            Q0FsbGJoenhXU29OWVN0ekoyZVc3WWMKLS0tIHpjVHdKTTFlS0ozanlBc0Rvazdu
            YVV4azA4SWRKa09FaUVQS1NUYk5EZTgKa3fW9HGTSOz/bHh1G1zxHza157NlAfli
            7jPHxlHHI1c8UZdfOF1CNyb79cdwjVJF1eqcm/pAX6PT/P/BCNwJiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:49:11Z"
    mac: ENC[AES256_GCM,data:AutMfvrFI6v2b3r4CtrYSB8iuOY5dUuXV5DTF7DNVlRrdjXQpwduSJH++CFB8kbqakPYJ2PZeXCEfFrkgVEcVocKbOXcuItK4/yhJXT0NPJWdLyXsT9TQzrEmeycrKCxyi1HyT0AkQBZVj323l/J1o6/ZDBl77WvcVMN3VvMLvc=,iv:r/QI5jNkvVnG1uC0JiazQFF3ag2o1ANicI2zGYUD4rk=,tag:JhCOFoMnlkrIaFhufx1LNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
