apiVersion: ENC[AES256_GCM,data:GbQ=,iv:YMQCw7yzFU02ATab4eNLWkbxApcoYb7LVc9ORStBL88=,tag:9WygstUdTzbL5hkPZAz/xQ==,type:str]
kind: ENC[AES256_GCM,data:jp/gJWcwysmp,iv:zYWNDFarax8rsxm9qrcZARFojz/VDvQ5so0GkbAYvP4=,tag:hLDziRfkQ0QHetH0qY4ukw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7fcOd6Hxlwzl,iv:59LGGFhb6mroys7Yo7WeDPq+m9mel7F0kHNoWe8UoB4=,tag:BqUPGQ3nS5Sr8x8SoLiXVg==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mi91SW43Z0lKMTJWSVA5
            NC82MmdKTjNiVEN4b0h1M3duZStEZ2VxNEUwCmJWKzRldFkycmlwM1JoOEc5TDZy
            N2hiYWVRbzVQNVgwcEd0c2pYVTRET28KLS0tIGJ5bjhPSzFZV3lVdUJlaDNTTWx0
            RUF0VXQ5Z0tmendxQmdkcWlSZ093cVkKTsjSMR4dUgvh8T65FCggQ1KO3Jwsi54g
            7YBWzqi/tRChfSqM5armZQg+x9MPtH75U1v829mFlM0lcHFVobNv/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T06:51:48Z"
    mac: ENC[AES256_GCM,data:qp4P3Y9HpBYZ7dxAPa78sGC7qvW1g37l0aswQS81XwHZti5yJdhhpKekCuVN751NLZ/pY36mfvR7l3Zwqtm8V/+HVuIgPY1oVzgdTMnHUdYJXjMgVrd+I4RnssLwRioRIApoVzvZmN5i2y8tWh3HD3K85FRN6jMwqFA/uK2Song=,iv:BNP6GMF9EpOcixHf+lZ5LbJDF3wH6xEtphpmKYR8Bq0=,tag:KWkfDscKRb4H2bnanHTIXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:GbQ=,iv:YMQCw7yzFU02ATab4eNLWkbxApcoYb7LVc9ORStBL88=,tag:9WygstUdTzbL5hkPZAz/xQ==,type:str]
kind: ENC[AES256_GCM,data:35o8RHo0,iv:bBq4FAzDPDg3gnszqbhsylxIV+FwVGArvxV5iFwTHpY=,tag:lx6fEb6Qo/QF+1itdLjg+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UjemXxMbQiH1eynuLxITL20=,iv:Wq+EMHMCPHA7/T4HMfOkKlBIfPShuRgTPvBr3SIdX5k=,tag:BZc5QTVEov/RXi1k8VvF6A==,type:str]
    namespace: ENC[AES256_GCM,data:6WobyvmRFyJO,iv:Idyz3JMFU2IvG6qBKk0ZoSeq0lM5mxvu7K9XXUqWIms=,tag:Q50shCXYVcypW2e18dHkhQ==,type:str]
type: ENC[AES256_GCM,data:buCm5NNW,iv:HKPV7JkAiqLOp+TeS5P9Dl+42gJDE0Tv+ota7rpCWes=,tag:7Al7W0n21I/EXVtdtznN+w==,type:str]
stringData:
    curseforge-api-key: ENC[AES256_GCM,data:5VehUzVz4NSdrvgRqsSBfKM4Nq5EQl1vMiuvmc1AMu3y9QEJ8+qyaxLw1LGx1JqHuyClBNka/YvQeUSv,iv:FcCSWrRdP3KTez6iWgTktAChEOZhgKI2mte9r8j4v3A=,tag:sqdx+b1JpFXfs9uZdy458Q==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mi91SW43Z0lKMTJWSVA5
            NC82MmdKTjNiVEN4b0h1M3duZStEZ2VxNEUwCmJWKzRldFkycmlwM1JoOEc5TDZy
            N2hiYWVRbzVQNVgwcEd0c2pYVTRET28KLS0tIGJ5bjhPSzFZV3lVdUJlaDNTTWx0
            RUF0VXQ5Z0tmendxQmdkcWlSZ093cVkKTsjSMR4dUgvh8T65FCggQ1KO3Jwsi54g
            7YBWzqi/tRChfSqM5armZQg+x9MPtH75U1v829mFlM0lcHFVobNv/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T06:51:48Z"
    mac: ENC[AES256_GCM,data:qp4P3Y9HpBYZ7dxAPa78sGC7qvW1g37l0aswQS81XwHZti5yJdhhpKekCuVN751NLZ/pY36mfvR7l3Zwqtm8V/+HVuIgPY1oVzgdTMnHUdYJXjMgVrd+I4RnssLwRioRIApoVzvZmN5i2y8tWh3HD3K85FRN6jMwqFA/uK2Song=,iv:BNP6GMF9EpOcixHf+lZ5LbJDF3wH6xEtphpmKYR8Bq0=,tag:KWkfDscKRb4H2bnanHTIXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
