apiVersion: ENC[AES256_GCM,data:7Fg=,iv:sAKXtSd3x9QsytejDhZZ1ZoKTrXJw3TfXp3edyZN01I=,tag:aF8hYCY/yOaWAyYg0ZW6RA==,type:str]
kind: ENC[AES256_GCM,data:kg+0+DpVAeY9,iv:3xTX7QiSqqZmwkK5aMU02UvXcY/XwyFqLfsBR7fMlGY=,tag:PPHQ2C8s8db2hVVLBqszeg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OfDJH3ALb+qeFRXMLaU=,iv:t0K9I9UpCEllU3axZa0cVypKzPG3eu/lh7+77ORUzWM=,tag:8o32uUGJwp5lHcRF0x/xTw==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UGwvNEtGYkJaNkxqYkR6
            S2VibjE5SWRkcnhDREFhR2MyYnovVm4vMTJvCmNxOGZEcmZzTHJhSkw4Rk5nQnZv
            cWtiUkhYZkdIeGhEblBEdHZHcUZRVDgKLS0tIFNMaThvTlpreXhndXBDZm9WenB3
            V0htRDBaM2k5djV4TzFOaWc5YkJrS1kKFe9OzrwzWVxOgUEu2ZAqKCH9PCmXvr27
            DTChiS6XBkbH6CqzBDMHQb4rLHw7gtRPFNaUUS5ndgG0v+/FrO6V3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T00:23:03Z"
    mac: ENC[AES256_GCM,data:ufo86y8Gx2q9zN7DoKRQtyZjEO0Z5brPWzfPTwMkEdUipsKT0bp0jXeorK7C8nuGLqSwR5uEvJIwIFwR3LYWejNyWd7ilu/anf+ExC4CAHEybtuA5DfGBpkWmpknPrgw/qONyTuT7K4y7Um/waoLJMFzfTsq4KcLu/CGohXI0sg=,iv:W35MY+1osIFZ8tvc+ZIxZKbd7XVUhS9XWqJ/vuaraj8=,tag:Vtl/twn5jKzHBVL+37jBSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:7Fg=,iv:sAKXtSd3x9QsytejDhZZ1ZoKTrXJw3TfXp3edyZN01I=,tag:aF8hYCY/yOaWAyYg0ZW6RA==,type:str]
kind: ENC[AES256_GCM,data:HmCSoQVo,iv:ZMQQsY6WmytyyCsPBGH0TgDNwO9gud9+B5/rSELGfAA=,tag:TqF9ClGEGRQov15ZEOjpxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sBzCoYVjd+aLdsr2c5rwDDp0,iv:yymteop4YGdwEpv9P7vqUVmFit7gzmIhJSOw/hsXMkc=,tag:GP+2871VGNY1VxwzHwDftA==,type:str]
    namespace: ENC[AES256_GCM,data:wu+qRSdmj30wkDY0/I0=,iv:x70hE/NldkcYl0KKtCjrOdpmZsEo1eiT3gpQ7sv/2mQ=,tag:biSy4XJfcNcBdlZKttUY+A==,type:str]
type: ENC[AES256_GCM,data:wG96RQ8Y,iv:74xAGucDY3nr+IBPsZlomfZEIRyVBfuUccQk467R87Q=,tag:zFXgFsHZCUbfjBh2L9VyvA==,type:str]
stringData:
    key: ENC[AES256_GCM,data:r6LiYZpqrj8GkhDE6/BIACrCqgkgN2L/BbDJLKz0gQ9Mgs/Seb16GEFVZEiJjbtI/Yw3ok7cT3kDm6+EkPy3FXLK,iv:V7+3Q7NXDfQ9UYgCKf3MaV2AEFDDzPMyzz+RZKXWfo8=,tag:Qp8ec6VzVodmkC+GLD2zlQ==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UGwvNEtGYkJaNkxqYkR6
            S2VibjE5SWRkcnhDREFhR2MyYnovVm4vMTJvCmNxOGZEcmZzTHJhSkw4Rk5nQnZv
            cWtiUkhYZkdIeGhEblBEdHZHcUZRVDgKLS0tIFNMaThvTlpreXhndXBDZm9WenB3
            V0htRDBaM2k5djV4TzFOaWc5YkJrS1kKFe9OzrwzWVxOgUEu2ZAqKCH9PCmXvr27
            DTChiS6XBkbH6CqzBDMHQb4rLHw7gtRPFNaUUS5ndgG0v+/FrO6V3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T00:23:03Z"
    mac: ENC[AES256_GCM,data:ufo86y8Gx2q9zN7DoKRQtyZjEO0Z5brPWzfPTwMkEdUipsKT0bp0jXeorK7C8nuGLqSwR5uEvJIwIFwR3LYWejNyWd7ilu/anf+ExC4CAHEybtuA5DfGBpkWmpknPrgw/qONyTuT7K4y7Um/waoLJMFzfTsq4KcLu/CGohXI0sg=,iv:W35MY+1osIFZ8tvc+ZIxZKbd7XVUhS9XWqJ/vuaraj8=,tag:Vtl/twn5jKzHBVL+37jBSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:7Fg=,iv:sAKXtSd3x9QsytejDhZZ1ZoKTrXJw3TfXp3edyZN01I=,tag:aF8hYCY/yOaWAyYg0ZW6RA==,type:str]
kind: ENC[AES256_GCM,data:HmCSoQVo,iv:ZMQQsY6WmytyyCsPBGH0TgDNwO9gud9+B5/rSELGfAA=,tag:TqF9ClGEGRQov15ZEOjpxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I2LNwXNDqq/+bV5Iv1ppW3Xl+j/1++oYv5jKTQ==,iv:mY2JUXLsjhRWiPBOK4Qr5DCT/Vg5hxiToGJJMKfigxQ=,tag:Ldec6hTGxzT60vXrDPkXUA==,type:str]
    namespace: ENC[AES256_GCM,data:wu+qRSdmj30wkDY0/I0=,iv:x70hE/NldkcYl0KKtCjrOdpmZsEo1eiT3gpQ7sv/2mQ=,tag:biSy4XJfcNcBdlZKttUY+A==,type:str]
type: ENC[AES256_GCM,data:wG96RQ8Y,iv:74xAGucDY3nr+IBPsZlomfZEIRyVBfuUccQk467R87Q=,tag:zFXgFsHZCUbfjBh2L9VyvA==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:iw0dLO8qfE5S9eTSL34J9si2PZSy5UEZFXji+RmQmh5s1/zUem8g5uQ8k/uD0Lh4Br7rcPtUs+vyCAEfbVmx1z2iYqgQI0m8rxaBTxcnsR89Xoat+KJkuEYH/HUALo62VIDPpXhYSsS1vq8U0Z1DoTy4abVwd8DGHHGn/lR4VJfIkr/lkE8zbqZsO4h0juS7z3j/1Rcys2yTLGgfH3l9gPrW817WaLz47K1ymt4FeBK9XA0Z6LTJJyBaWPfqKYZl+HfCbxM0GjeUFX2eK6+0w0/I0u21GNpKpfpq/NRbjynPVgJcals64QkC7jpvlYQBSEAtzqp13zKBlgMXDUc4u74QaWhWY3KL1q6hnR3rg7+1tzDp02n3YR4ZP7l3QGAhEiZDm/r+picbZaVjPXq3n3EUBvVWWh8e76Y4NaltDSYyPRer633C8uVYlvd0Q9tfawigKMEOWp3pER2PC8twgCT9qSQjuLfc8WCY1eEmUnAetXV+/twcUmhHgnonXnpH5tglhkfO+dKNAWiq2z/KumbsQXrIejNkjOhlT7weOMfkrL7mOU3cXvmMpBe70wUtS2ZnEbTV7mYtn3/kJjbS6Z2R9xD1ECQTFwq2sxzHOrlIAY6u2+i9iwM2QhxlshE/fculwsJYQcaUXWYB3x66LdTVMW5Cx3i3mBbHBjzQ1kz3QAQmrux+KPBt4tyq6PsUIzoLOSTdp24ryfD37yU6ejJ0abNzOz/gIUQ9ir+cufP3bpvShI9aDH9nuXMuMIPDeFLeaeVpBiqcicDELH9pOpjQEWHOF1X6wloHsQ4VI3B37RlNgSQZhZDntsDXw131JAeCho8jJjsqQeUKQh1hTPi0OUql28B0/JRbsQLyx9upuPbK,iv:mbu3SgymZUw7NMCLhd71gEa29OjuhaOaV9oK2JNH6F4=,tag:ydHehYfnqJDlyWavk1xUDw==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UGwvNEtGYkJaNkxqYkR6
            S2VibjE5SWRkcnhDREFhR2MyYnovVm4vMTJvCmNxOGZEcmZzTHJhSkw4Rk5nQnZv
            cWtiUkhYZkdIeGhEblBEdHZHcUZRVDgKLS0tIFNMaThvTlpreXhndXBDZm9WenB3
            V0htRDBaM2k5djV4TzFOaWc5YkJrS1kKFe9OzrwzWVxOgUEu2ZAqKCH9PCmXvr27
            DTChiS6XBkbH6CqzBDMHQb4rLHw7gtRPFNaUUS5ndgG0v+/FrO6V3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T00:23:03Z"
    mac: ENC[AES256_GCM,data:ufo86y8Gx2q9zN7DoKRQtyZjEO0Z5brPWzfPTwMkEdUipsKT0bp0jXeorK7C8nuGLqSwR5uEvJIwIFwR3LYWejNyWd7ilu/anf+ExC4CAHEybtuA5DfGBpkWmpknPrgw/qONyTuT7K4y7Um/waoLJMFzfTsq4KcLu/CGohXI0sg=,iv:W35MY+1osIFZ8tvc+ZIxZKbd7XVUhS9XWqJ/vuaraj8=,tag:Vtl/twn5jKzHBVL+37jBSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
