apiVersion: ENC[AES256_GCM,data:asg=,iv:j0FsK1CI5VdPOERWlMNJ/37Apg5HQkOJDUAfNTlFbk4=,tag:lYNGSj128mKnWX7O/99HWw==,type:str]
kind: ENC[AES256_GCM,data:CUeiyGvi7ePg,iv:HxxKYbCTA2GNVh2ghxZ5GWt/OXan7gg5c6mh3NOyySI=,tag:ud626VlYshftk9cTMh+dhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ktzLAe2sjFen,iv:ymB1GvpoZqFZOZGC9mOZMOTtImOj+GP7025VUFnyTgI=,tag:JB28yf9WyHCXxLX/75bshA==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYnZHdVF5OWlZV0JTc2RH
            bzFtRjd5NlR3Mm5OWU5vVW9JVlN0ZmFWaWswCit4WGV5UGdyeG1qKzk1RFpNdVBa
            UHJETEViK1lIYzR6RWpXWkhWVWZNQ00KLS0tIDNiUVhCdk5UOFhTYmo3S0VwYk1v
            QkVUaFYvZnhXaUtWWkc5WnJ1N2hFdFEKgue55W4NQuW8SmZvAdxTXgMgYLKmyQdC
            DtUGZ6xQFAKpFRPcpddc6vtRtTBv2MTBremwPE6N0a/G1DePWlFT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:20:22Z"
    mac: ENC[AES256_GCM,data:pvNVCniZpPyRtDGOmMLyMogfS7nFLVS75UCQVsQXkJ9lO8oy7jBhVGOeHdysGgYz4zHuaVq/HSOS+FfJrMrSExo6XrPhEE2AhWWFSRQzsoM1bRy3QLJbjUTFdP7kykd/O+MU8WrsXXox0qR7JDkEsfL2ZRKTJL9EhtroiWBznVU=,iv:I7j+pVybEGn051oPrOTpc8E4BmhRbfuLyCTfrBT0h1g=,tag:rFwf5KogWfx+yUPzxqljUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:asg=,iv:j0FsK1CI5VdPOERWlMNJ/37Apg5HQkOJDUAfNTlFbk4=,tag:lYNGSj128mKnWX7O/99HWw==,type:str]
kind: ENC[AES256_GCM,data:awhYW9wo,iv:zidsWVL7VxESB3rewIGJyEsLmTcNLEe/S3rH1F/Ci3I=,tag:gHDk0f7wEvgms6urjbkPEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:usEimgT4gzewB8jPvs9u,iv:bmZ63FW+34L/KU5sKPQTIH1vCcCuMF1uuugCOZwF2OE=,tag:zeeRdG6SzygwOcL01tUrZQ==,type:str]
    namespace: ENC[AES256_GCM,data:H0rAgtW1ltO7,iv:JjK5QxN5/XyayGdpTKk+ywpVSbgD+KxaPCZjohujN+E=,tag:4v3i9q82TDFjcgWmv5Ihdw==,type:str]
type: ENC[AES256_GCM,data:Btxs1+wZ,iv:R+qqzUsv/5OHoqypXsIyoOj8AHzoe/ClxiJsW8I9+e8=,tag:wijmGzw96NhSR9NulE6XXw==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:OxLyqwr4yA==,iv:SREsVsGAXyPUcPqXA36Rhtp9aqnpT8ec+XKorOU54Kc=,tag:3CACINJFjOI2kM+qZ8+tfw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:/bBas1B4KAE=,iv:wA9nDRLPQhOIoHYoQmwaNnK3U3ihQ5vu9Xevn4GaI44=,tag:aEvAzP8bZ7Au8P+qDbUbaw==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYnZHdVF5OWlZV0JTc2RH
            bzFtRjd5NlR3Mm5OWU5vVW9JVlN0ZmFWaWswCit4WGV5UGdyeG1qKzk1RFpNdVBa
            UHJETEViK1lIYzR6RWpXWkhWVWZNQ00KLS0tIDNiUVhCdk5UOFhTYmo3S0VwYk1v
            QkVUaFYvZnhXaUtWWkc5WnJ1N2hFdFEKgue55W4NQuW8SmZvAdxTXgMgYLKmyQdC
            DtUGZ6xQFAKpFRPcpddc6vtRtTBv2MTBremwPE6N0a/G1DePWlFT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:20:22Z"
    mac: ENC[AES256_GCM,data:pvNVCniZpPyRtDGOmMLyMogfS7nFLVS75UCQVsQXkJ9lO8oy7jBhVGOeHdysGgYz4zHuaVq/HSOS+FfJrMrSExo6XrPhEE2AhWWFSRQzsoM1bRy3QLJbjUTFdP7kykd/O+MU8WrsXXox0qR7JDkEsfL2ZRKTJL9EhtroiWBznVU=,iv:I7j+pVybEGn051oPrOTpc8E4BmhRbfuLyCTfrBT0h1g=,tag:rFwf5KogWfx+yUPzxqljUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:asg=,iv:j0FsK1CI5VdPOERWlMNJ/37Apg5HQkOJDUAfNTlFbk4=,tag:lYNGSj128mKnWX7O/99HWw==,type:str]
kind: ENC[AES256_GCM,data:awhYW9wo,iv:zidsWVL7VxESB3rewIGJyEsLmTcNLEe/S3rH1F/Ci3I=,tag:gHDk0f7wEvgms6urjbkPEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IqsbjS1qRRtNaUjS0E5IaLPWgzKudzus,iv:i8TrHiNoHsMJ+KdRvNmBae/3evNHwrdAVSYtFrElO8w=,tag:6M0R7JO+/qLt7BH/YkSnpA==,type:str]
    namespace: ENC[AES256_GCM,data:H0rAgtW1ltO7,iv:JjK5QxN5/XyayGdpTKk+ywpVSbgD+KxaPCZjohujN+E=,tag:4v3i9q82TDFjcgWmv5Ihdw==,type:str]
type: ENC[AES256_GCM,data:Btxs1+wZ,iv:R+qqzUsv/5OHoqypXsIyoOj8AHzoe/ClxiJsW8I9+e8=,tag:wijmGzw96NhSR9NulE6XXw==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:/4Fnb1dSwA==,iv:waf4dIpMIKuTkV0J7E2jk/B3gWk0vZPuu4+PIaxqrDI=,tag:CG/0vH7Sxkq0QeKO4EuUWw==,type:str]
    secretKey: ENC[AES256_GCM,data:jDp1NGgBvEs=,iv:bVtGpgGQCvHXCMw0rIdqO0cy8tmSkCpMuZZDqoNe5t4=,tag:HEkJY5VO14nfiOI0J6NEPQ==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYnZHdVF5OWlZV0JTc2RH
            bzFtRjd5NlR3Mm5OWU5vVW9JVlN0ZmFWaWswCit4WGV5UGdyeG1qKzk1RFpNdVBa
            UHJETEViK1lIYzR6RWpXWkhWVWZNQ00KLS0tIDNiUVhCdk5UOFhTYmo3S0VwYk1v
            QkVUaFYvZnhXaUtWWkc5WnJ1N2hFdFEKgue55W4NQuW8SmZvAdxTXgMgYLKmyQdC
            DtUGZ6xQFAKpFRPcpddc6vtRtTBv2MTBremwPE6N0a/G1DePWlFT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:20:22Z"
    mac: ENC[AES256_GCM,data:pvNVCniZpPyRtDGOmMLyMogfS7nFLVS75UCQVsQXkJ9lO8oy7jBhVGOeHdysGgYz4zHuaVq/HSOS+FfJrMrSExo6XrPhEE2AhWWFSRQzsoM1bRy3QLJbjUTFdP7kykd/O+MU8WrsXXox0qR7JDkEsfL2ZRKTJL9EhtroiWBznVU=,iv:I7j+pVybEGn051oPrOTpc8E4BmhRbfuLyCTfrBT0h1g=,tag:rFwf5KogWfx+yUPzxqljUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
