apiVersion: ENC[AES256_GCM,data:SPY=,iv:AaCoCYrxxshNT+Y3+r67QjO5YN2QLBUDBT99z7J3Pvs=,tag:gaYsj9XzsqDSveVPWBK5sA==,type:str]
kind: ENC[AES256_GCM,data:nNVIqufHwymg,iv:bDUDMwLggYxLEDainhZ8GoOM6OxqEwG1vLpwWHn/gd0=,tag:bvVVqGgxgjYIq4gDwewKxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t2Z6KqsZAUIN,iv:OV6JiJ/N0BvSw1WZkBewUjwTSj0C1E8YEsG9Ai6Ygwc=,tag:CA/kmseJCqetGLGncGwSRg==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjlmME54alUxTEpVUXdo
            RmVETG5ZT0U4Nys1eERjbXNId2F1Yy9HQVJrCjg3WnAwNlVmOGhta0VzK2doUWJ5
            dWIrd1g4Sy9OemMwelh3UDV3R2h3dDgKLS0tIGc3akpoeHg3ZEcwQ0lleXJYUEc4
            LytaVEJKd1RDTXNVaDFHN1NHTVMrOVUKwG84PGpDOP7MSVE3CaSXrEX+moEr8CFc
            boH+Y7nlnDNY84G7nbjIl3nLb4AvU8b2nYzwcRqP521IWTFnQ5xeXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T00:20:01Z"
    mac: ENC[AES256_GCM,data:ozVLoYY4mB2z+d+UNJz0rU2FQJ4M+CBv26ayKWIXJIg9cuxK/xxFkR0+pOR8pXD9qHCt6it9s+2DA/higLDzLpIU+aQo9997BENfQIqRekmZCdv/FZ+f2P2SfzyInhCzmiS4G0C5kmVSOAqpeE9rXceGKyiSegUFekN+CN81Puw=,iv:Zm9eNY7QzOrsFC16E9JvvZVlukT4UxOfVvNN9vBijjw=,tag:cdcXqUHMtFH8CKA/aHqVwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:SPY=,iv:AaCoCYrxxshNT+Y3+r67QjO5YN2QLBUDBT99z7J3Pvs=,tag:gaYsj9XzsqDSveVPWBK5sA==,type:str]
kind: ENC[AES256_GCM,data:nNVIqufHwymg,iv:bDUDMwLggYxLEDainhZ8GoOM6OxqEwG1vLpwWHn/gd0=,tag:bvVVqGgxgjYIq4gDwewKxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6NZ9Ijtdxe01qLby3gg2hgNy,iv:IC1b3uVuvjB7yhdxSUpmBCZ5P5xdgE8yRAgY3lPt5Vo=,tag:BolYCymuAUspsK/I06ur1A==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjlmME54alUxTEpVUXdo
            RmVETG5ZT0U4Nys1eERjbXNId2F1Yy9HQVJrCjg3WnAwNlVmOGhta0VzK2doUWJ5
            dWIrd1g4Sy9OemMwelh3UDV3R2h3dDgKLS0tIGc3akpoeHg3ZEcwQ0lleXJYUEc4
            LytaVEJKd1RDTXNVaDFHN1NHTVMrOVUKwG84PGpDOP7MSVE3CaSXrEX+moEr8CFc
            boH+Y7nlnDNY84G7nbjIl3nLb4AvU8b2nYzwcRqP521IWTFnQ5xeXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T00:20:01Z"
    mac: ENC[AES256_GCM,data:ozVLoYY4mB2z+d+UNJz0rU2FQJ4M+CBv26ayKWIXJIg9cuxK/xxFkR0+pOR8pXD9qHCt6it9s+2DA/higLDzLpIU+aQo9997BENfQIqRekmZCdv/FZ+f2P2SfzyInhCzmiS4G0C5kmVSOAqpeE9rXceGKyiSegUFekN+CN81Puw=,iv:Zm9eNY7QzOrsFC16E9JvvZVlukT4UxOfVvNN9vBijjw=,tag:cdcXqUHMtFH8CKA/aHqVwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:SPY=,iv:AaCoCYrxxshNT+Y3+r67QjO5YN2QLBUDBT99z7J3Pvs=,tag:gaYsj9XzsqDSveVPWBK5sA==,type:str]
kind: ENC[AES256_GCM,data:oPapYTaE,iv:zISR2K7AQzrkOw3R/9bGQ377UPVOPSAVBWakV/kU8k0=,tag:dGOoRvj1WslYiv6jD+r5Og==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mPmjjo9TMEtaVl/eej4M,iv:KXvOWNHL5OP/Nw1rxJ5flNXvlC93Ri+hzCNj0Cm6Z70=,tag:b1Tf6Lnp47EAAB1dFSi5OQ==,type:str]
    namespace: ENC[AES256_GCM,data:90t2ukvDGkLt,iv:TB1/CVty39+ffv2xWcuhg/zSujgLqv9pOFdM4xrkAOg=,tag:TYWGP0a8u9W6xnnsuw2Ajw==,type:str]
type: ENC[AES256_GCM,data:n9YvdrVD,iv:vrFrdz3ynUTJ1+I7jun1NfNj/+FSlyILStJUKK3ZMkQ=,tag:9peHwa2Pzca2MEaLN8ZeqQ==,type:str]
stringData:
    playitgg-api-key: ENC[AES256_GCM,data:p8pATLVhhUKkyv5RhNugkr27kjUQviQVIF0J7xRidbxeo3KucksCrVh5FUgp/iQyIIApS0C/UTwJGXRujlqcxg==,iv:XL+k+rTdyUsihWqlSwnpbkfYRQGVyW1LF2klZvujVHE=,tag:ubqNcRNFc1leahc1rd0F6w==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjlmME54alUxTEpVUXdo
            RmVETG5ZT0U4Nys1eERjbXNId2F1Yy9HQVJrCjg3WnAwNlVmOGhta0VzK2doUWJ5
            dWIrd1g4Sy9OemMwelh3UDV3R2h3dDgKLS0tIGc3akpoeHg3ZEcwQ0lleXJYUEc4
            LytaVEJKd1RDTXNVaDFHN1NHTVMrOVUKwG84PGpDOP7MSVE3CaSXrEX+moEr8CFc
            boH+Y7nlnDNY84G7nbjIl3nLb4AvU8b2nYzwcRqP521IWTFnQ5xeXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T00:20:01Z"
    mac: ENC[AES256_GCM,data:ozVLoYY4mB2z+d+UNJz0rU2FQJ4M+CBv26ayKWIXJIg9cuxK/xxFkR0+pOR8pXD9qHCt6it9s+2DA/higLDzLpIU+aQo9997BENfQIqRekmZCdv/FZ+f2P2SfzyInhCzmiS4G0C5kmVSOAqpeE9rXceGKyiSegUFekN+CN81Puw=,iv:Zm9eNY7QzOrsFC16E9JvvZVlukT4UxOfVvNN9vBijjw=,tag:cdcXqUHMtFH8CKA/aHqVwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:SPY=,iv:AaCoCYrxxshNT+Y3+r67QjO5YN2QLBUDBT99z7J3Pvs=,tag:gaYsj9XzsqDSveVPWBK5sA==,type:str]
kind: ENC[AES256_GCM,data:oPapYTaE,iv:zISR2K7AQzrkOw3R/9bGQ377UPVOPSAVBWakV/kU8k0=,tag:dGOoRvj1WslYiv6jD+r5Og==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mPmjjo9TMEtaVl/eej4M,iv:KXvOWNHL5OP/Nw1rxJ5flNXvlC93Ri+hzCNj0Cm6Z70=,tag:b1Tf6Lnp47EAAB1dFSi5OQ==,type:str]
    namespace: ENC[AES256_GCM,data:PvtmHWXvW18WIcIKHYSH7dxV,iv:kpSDLbvTuYQAG7yN5EXBlvQRAexvcKJ8IsPo0Sr4xWQ=,tag:PXRZudvc1HXY0oDZPklq9Q==,type:str]
type: ENC[AES256_GCM,data:n9YvdrVD,iv:vrFrdz3ynUTJ1+I7jun1NfNj/+FSlyILStJUKK3ZMkQ=,tag:9peHwa2Pzca2MEaLN8ZeqQ==,type:str]
stringData:
    playitgg-api-key: ENC[AES256_GCM,data:9qKeJjKOMJ5JdWlORYbiRMxUj/GewRUfwi294rEK6ebhrOLLHD0zy3KqfQulJA/MnVs1o2q7HowFqWAVbWL0MA==,iv:slFGgJdGHFIMv3D87wfLeFJEgPzElLD3HWIaC5ODdLs=,tag:BCTp23WeHAU7jLqNS0eodg==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjlmME54alUxTEpVUXdo
            RmVETG5ZT0U4Nys1eERjbXNId2F1Yy9HQVJrCjg3WnAwNlVmOGhta0VzK2doUWJ5
            dWIrd1g4Sy9OemMwelh3UDV3R2h3dDgKLS0tIGc3akpoeHg3ZEcwQ0lleXJYUEc4
            LytaVEJKd1RDTXNVaDFHN1NHTVMrOVUKwG84PGpDOP7MSVE3CaSXrEX+moEr8CFc
            boH+Y7nlnDNY84G7nbjIl3nLb4AvU8b2nYzwcRqP521IWTFnQ5xeXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T00:20:01Z"
    mac: ENC[AES256_GCM,data:ozVLoYY4mB2z+d+UNJz0rU2FQJ4M+CBv26ayKWIXJIg9cuxK/xxFkR0+pOR8pXD9qHCt6it9s+2DA/higLDzLpIU+aQo9997BENfQIqRekmZCdv/FZ+f2P2SfzyInhCzmiS4G0C5kmVSOAqpeE9rXceGKyiSegUFekN+CN81Puw=,iv:Zm9eNY7QzOrsFC16E9JvvZVlukT4UxOfVvNN9vBijjw=,tag:cdcXqUHMtFH8CKA/aHqVwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
