apiVersion: ENC[AES256_GCM,data:jt0=,iv:Oeqag0z16Ey1A4WxxDV+DebFtPdOe6WJU18vEIumAXQ=,tag:J9GP9PMLV9587JS7ED0l2A==,type:str]
kind: ENC[AES256_GCM,data:va69jTPW,iv:Dud0DtL1/xuyVkyqxgdBBzmZb636eTIXwr3TDOpBtFU=,tag:fliaaxtt+Vm9pedazO48JA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1LxW8XvoLtzVJWzsp3UyblR0KQ==,iv:2iko7Ud6F3UBL7onQ9TI94cRnrw7IIc2ebuoc822F58=,tag:Tn8qKmJhaqPgvlwz3/3PdQ==,type:str]
    namespace: ENC[AES256_GCM,data:EXhRlQnavslJPIA=,iv:7NGo0vtxxn9n6luQsrBKNuEbeK7FWs6gSFwmI7oxCxc=,tag:LJif1I/ERPdmp7U5d/BdXw==,type:str]
type: ENC[AES256_GCM,data:4WpvAWLR,iv:KjOB7w2kWaL26PG2+Oprd6Zhq7EawcOghL5IYIBM/pg=,tag:YudRsUDWpxFHo1IlC5iYjQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:FeGlV6siiDMyTwGloRSVRei/Fe5H,iv:kGmrJ7XdRSZ6MkLL0V8ob1px+qfsd3yu5K0ZnD5W7jw=,tag:q7BfnCeF9g/3rwPLgR9hIQ==,type:str]
    secret-api-key: ENC[AES256_GCM,data:be7TjWoFDbgqTtTdPgHjqAXV4mjvMVFI,iv:xE7k8BpwNNhM7OofIU7EchehBIEtjlvAfKaxE4XTN0E=,tag:qRulrK617SVCzK42+Tv5fQ==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS1RENmNqV3pNa1VQTFYy
            b3dXa0NIUk5ycUozYTRVL0diQUhuMHdxNFhZCmk3bHZVTm9QR0YwZ29adVBIWERa
            VVVCclRlV1N5bVFxQ0h1cFpld3lzR1EKLS0tIDJiUjVZVWZyN25QdmRhTS9xRHpU
            SXJDNGlCUXQ1Z0paTGF4bXpsTHVLcW8KNk2I+o5vjnp9YXlazm6prTEC5IDxM8hZ
            CypkxecsQHpKykDAxekmXPcy303X1oqlfOjfWoGJ1myiYDg/261K6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T01:05:49Z"
    mac: ENC[AES256_GCM,data:4UgUp3KLo1JLIjwM9e/vfRhIKeHHp3VqPxnrE/ZHPGFtG2Ky0mDeuHD0mYHu8aV6iwfXZmtq6wh/+6xVktzP2TJrP7fTnWJZeamO3H2mrli6EQxvGv9SSGUFqE4jnMBjpmjCypMGzp4Ta9IzgyGFttxNjISsDIKkoMNafDehmkM=,iv:nnPKFsm7xlylvkWDc7DH/UDhdKFXXDPrT5zHL1zLryY=,tag:BGFn+h8MjkljjAKKibANXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
