apiVersion: ENC[AES256_GCM,data:jt0=,iv:Oeqag0z16Ey1A4WxxDV+DebFtPdOe6WJU18vEIumAXQ=,tag:J9GP9PMLV9587JS7ED0l2A==,type:str]
kind: ENC[AES256_GCM,data:va69jTPW,iv:Dud0DtL1/xuyVkyqxgdBBzmZb636eTIXwr3TDOpBtFU=,tag:fliaaxtt+Vm9pedazO48JA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1LxW8XvoLtzVJWzsp3UyblR0KQ==,iv:2iko7Ud6F3UBL7onQ9TI94cRnrw7IIc2ebuoc822F58=,tag:Tn8qKmJhaqPgvlwz3/3PdQ==,type:str]
    namespace: ENC[AES256_GCM,data:EXhRlQnavslJPIA=,iv:7NGo0vtxxn9n6luQsrBKNuEbeK7FWs6gSFwmI7oxCxc=,tag:LJif1I/ERPdmp7U5d/BdXw==,type:str]
type: ENC[AES256_GCM,data:4WpvAWLR,iv:KjOB7w2kWaL26PG2+Oprd6Zhq7EawcOghL5IYIBM/pg=,tag:YudRsUDWpxFHo1IlC5iYjQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:QzZyZrpTjWOy38ntSV6kUyRu8K4XkYnr+xwNTXRxx6lx3+kq5ze3i8z0JTSkkzgr/UitCYBno+cyR+VmLuxoA5W0C54=,iv:BdBjsFpl2A2pURUkSw5A9cBRJRjZEnC808GQBosEt2w=,tag:2c0+XevVHXc9HrrRgdAIbw==,type:str]
    secret-api-key: ENC[AES256_GCM,data:AA0+N2UnPjlcu2eG1SBvfVgPzfI9kx1RdqVKdd5eMscMm9OcUYd/+0Y8N0o0yIhe6d55k3YKtBWwd9Tx0PyeOzRjAPs=,iv:3aCCGXJtbPNgeEf/xQVUN+iwZJg+xeDVj93GLLWiJg0=,tag:QaYCfNPTo2UKnFDGwfYZtA==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS1RENmNqV3pNa1VQTFYy
            b3dXa0NIUk5ycUozYTRVL0diQUhuMHdxNFhZCmk3bHZVTm9QR0YwZ29adVBIWERa
            VVVCclRlV1N5bVFxQ0h1cFpld3lzR1EKLS0tIDJiUjVZVWZyN25QdmRhTS9xRHpU
            SXJDNGlCUXQ1Z0paTGF4bXpsTHVLcW8KNk2I+o5vjnp9YXlazm6prTEC5IDxM8hZ
            CypkxecsQHpKykDAxekmXPcy303X1oqlfOjfWoGJ1myiYDg/261K6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T01:26:29Z"
    mac: ENC[AES256_GCM,data:aiIccwgOqaROd7+gxkgArwuXM2zRDB132kOOoof49NmKCpCNQLWLOeSN5ZlnRQP+39kN7OclIAKqMqy1j42IgMQX2mPr8Hj51AiYMr79XR1kTcdIMe/AM/UKFw2ar8fLkLwqrowLxLDLCiHAbCu05nO43FAS2wXLyxYolL6Jwis=,iv:/XC2fewao8v0xydN/h4d2PFZ5WzT0RZvjoxHtEgRKCs=,tag:0mJrm4LJvz/B0yEclpOggg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
