apiVersion: ENC[AES256_GCM,data:ncg=,iv:efmJ+bdlfhuUI64hf78nI3+NEZMvrcjZfJvd08dYMt4=,tag:3mPfjIphyPhpZQfO1YN+Bg==,type:str]
kind: ENC[AES256_GCM,data:vN0uSL4Q,iv:Ay0J34xUDMF/9SO7pvR+qwqse+zoP3Wnu6OtuE9PgDA=,tag:q8ov4olJfUUjLLSuir1r4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W4HFdbEq+pjgqFWqcBg=,iv:q6uZzTSdbO34/ox707xIYKd5znd72GsiAu0Em1dZWpk=,tag:y0E3rnjNg0VtmhC6cHW5ag==,type:str]
    namespace: ENC[AES256_GCM,data:t3Q9MaM25f1l,iv:QuojLeiFWO+9Quy0W8q3o7raRf7pnxnlB5gFpv/DdXo=,tag:zPBHX2jmBqRn+oWGbJRAmw==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:Uy4ixBKiKBpxSK2DsR1vLZs=,iv:osMNhPq0eXyMqaSYRUAtZLKEjA1v7no1IiVslHs1CA4=,tag:b5kzQGCXOwTtp3VEH4tuIg==,type:str]
    client_secret: ENC[AES256_GCM,data:0hEXn1xUiFsZhAbBNDQmE24zAiLgle/j2VhZsxFyKs2mwYIcsJKy0ytpAQb1hnrFhE0HIX8+WYL1KTvLqr+a4w==,iv:Bu0ahe2OSjXWKbKJ1g/6aGvNIbPlKNV6PBOki7VlmQs=,tag:neSwaIj9oOIFwmzu5bv0vA==,type:str]
sops:
    age:
        - recipient: age1rxv0he8xyeavww25fjdx2y2942ggk5smf4y9v3wakejq4xhu43zq5uyt57
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUmVOM3A3YzJQT29GcjVV
            c2VpT2J4YitQakxoeDVCd2kvNGFvN09zM2lZCmIrN1YwSDFYK1h1T1ZSZEpXM3JL
            OWtHR0N5eEJGVGRZSDNISWZGaU9NQ1UKLS0tIGRVY1VSN3VaMFZmK05SNmUrVndr
            SE1lWTNaZmRkYm5JTVA5Y3FKOGlxYncKrKOFbm06W/uvzq5sCcMVe43LNh4a8uMb
            W1F8OaYzsln+AEiJkisWgJVEDKx/HDdBw92oCfu2ULWO/0jCXTXRow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T03:46:17Z"
    mac: ENC[AES256_GCM,data:PN+zwL658zQHKxhR7EvDk+dMWJQus+GdZp+qXXTN6W0O2o4Q7pdwevkKd0cef6aP26nXlcVtWoQtCxooqWUFBXzaCb1fQEzuK63NKu00k2LAt1UD7QLXrPNlVyeHIQt5/e/wfbMCc1M2Wvcs34zL4mCC0eXb0r3fyyO8y0WVwXU=,iv:I0nNIe44q12bPMR1Z+FHWmrG/bNvl5p++7YL9ol8TR4=,tag:zDONKuGpPBe6G7Q4m0YuNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
